version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=rise
      - POSTGRES_PASSWORD=rise
    volumes:
      - dbdata:/data/postgres
    networks:
      - rise-network

  app:
    depends_on:
      - db
    build:
      context: .
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: production
      PRISMA_DATABASE_URL: postgresql://postgres:rise@db:5432/rise?schema=public
      ADDRESS: 0.0.0.0
    networks:
      - rise-network

networks:
  rise-network:
    driver: bridge

volumes:
  dbdata:
